void tree1r() {
    // read the Tree generated by tree1w and fill two histograms
    // note that we use "new"  to create the TFile TTree objects,
    // to keep them alive after leaving this function
    TFile *f = new TFile("tree1.root");
    TTree *t1 = (TTree*)f->Get("t1");
    Float_t px, py, pz;
    Double_t random;
    Int_t ev;
    t1->SetBranchAddress("px", &px);
    t1->SetBranchAddress("py", &py);
    t1->SetBranchAddress("pz", &pz);
    t1->SetBranchAddress("random", &random);
    t1->SetBranchAddress("ev", &ev);
    //create two histograms
    TH1F *hpx   = new TH1F("hpx","px distribution", 100,- 3, 3);
    TH2F *hpxpy = new TH2F("hpxpy", "py vs px", 30, -3, 3, 30, -3, 3);
    //read all entries and fill the histogram
    Int_t nentries = (Int_t)t1->GetEntries();
    for (Int_t i=0; i<nentries; i++) {
        t1->GetEntry(i);
        hpx->Fill(px);
        hpxpy->Fill(px, py);
    }

    TCanvas *c1 = new TCanvas("c1","two canvas", 700, 900);
    c1->Divide(2,1);
    c1->cd(1);
    hpx->Draw();
    c1->cd(2);
    hpxpy->Draw();
    c1->SaveAs("histogram.png");
    // We do not close the file. We wand to keep the generated
    // histograms we open a browser and the TreeViewer
    if (gROOT->IsBatch()) return;
    new TBrowser ();
    //t1->StartViewer();

    //In the browser, click on "ROOT Files",  then on "tree.root"
    //You can click on the histogram icons in the right panel to draw
    //them in the TreeViewer, follow the instructions in the help

}